feat: Sankey graph component
hestiaAI/hestialabs-experiences pull request #224
Opened 2021-11-18 16:33 UTC by fquellec

New visualisation component for displaying data that follows a graph structure. Already included on Uber experience in this PR. This component takes as props data of the form: 
values : [{ source: 'A', target: 'B', value: 2},  ...]

preview: 
![image](https://user-images.githubusercontent.com/17878016/142456684-d68338bb-8827-4000-a2f4-babe05f964fe.png)

2021-11-19 08:31 UTC, ffsinger requested changes
The graph looks good, but there's a weird bug:

If I hover one of the nodes, there seems to be a global CSS change and many icons on the page become almost transparent (the run buttons, home icon, menu icon, share icons, ...). In addition, the color of the nodes stay lighter even when the mouse leaves.

2021-11-22 16:42 UTC, fquellec commented
> The graph looks good, but there's a weird bug:
> 
> If I hover one of the nodes, there seems to be a global CSS change and many icons on the page become almost transparent (the run buttons, home icon, menu icon, share icons, ...). In addition, the color of the nodes stay lighter even when the mouse leaves.

fixed in [#a0abb1e](https://github.com/hestiaAI/hestialabs-experiences/pull/224/commits/a0abb1e624fc291510fdc40fb0bed3db361c6f6b)

2021-11-22 16:51 UTC, streitlua approved these changes
I only tested on the sample data, but it looks good to me!

2021-11-22 16:56 UTC, ffsinger approved these changes

2021-11-22 16:57 UTC, merged