feat: added a summary of the files in the file viewer and moved it to the top
hestiaAI/hestialabs-experiences pull request #278
Opened 2021-12-03 16:08 UTC by streitlua

Changes:
- added a summary of the files uploaded by the user:
![image](https://user-images.githubusercontent.com/16099301/144634057-df2949f0-ac45-42c4-82cc-8b101eec9558.png)
- added an util function to convert a size in bytes into a human readable string

Related issues:
- (https://github.com/hestiaAI/digipower-data-experiences/issues/70)
- (https://github.com/hestiaAI/digipower-data-experiences/issues/71) 

Remarks:
- Alex mentioned showing the number of datapoints in the files, but this is impossible to define generically in my opinion.
What do you think?

2021-12-06 11:03 UTC, valentinoli commented
> * Alex mentioned showing the number of datapoints in the files, but this is impossible to define generically in my opinion.

I agree. It seems very subjective and difficult to compute and hard to maintain long term

2021-12-06 11:21 UTC, ffsinger requested changes
It's nice ! 

As we discussed, maybe we could also show the size of selected files

2021-12-06 11:21 UTC, ffsinger commented on components/unit/file-explorer/UnitFileExplorer.vue
> -                :selectable="selectable"
The files are not selectable anymore, this is a merging mistake

2021-12-06 11:21 UTC, ffsinger commented on components/unit/file-explorer/UnitFileExplorer.vue
> +        ([ext, count]) => `${count} ${ext}${count === 1 ? '' : 's'}`
I don't like this format: it's weird to see "3 jss" or "5 jsons", I'd rather write "3 .js" and "5 .json"

2021-12-06 12:57 UTC, alexbfree commented
Added some feedback; see hestiaAI/digipower-data-experiences/issues/71

2021-12-06 13:08 UTC, valentinoli commented
> As we discussed, maybe we could also show the size of selected files

You can borrow/change this function from another project of mine that converts bytes to a size string

```
bytesToSizeString (bytes) {
  if (!bytes) {
    // just in case
    return ''
  }
  const kilo = 1024
  const kiloBytes = Math.floor(bytes / kilo)
  let sizeString = `${kiloBytes} KB`
  if (kiloBytes >= kilo) {
    // express in MB if >= 1024 KB
    const megaBytes = Number.parseFloat(kiloBytes / kilo).toFixed(1)
    sizeString = `${megaBytes} MB`
  }
  // surround with parentheses
  return `(${sizeString})`
}
```

2021-12-06 13:36 UTC, streitlua commented
> You can borrow/change this function from another project of mine that converts bytes to a size string

Thanks! We have a similar function in `utils.js` already :)

2021-12-07 13:07 UTC, fquellec approved these changes
Everything looks good to me, some UI to fix later but that's not the priority.. Well done !

2021-12-07 13:23 UTC, ffsinger approved these changes

2021-12-07 13:24 UTC, merged