fix(i18n): #932
hestiaAI/hestialabs-experiences pull request #940
Opened 2022-08-22 12:18 UTC by valentinoli

2022-08-23 08:20 UTC, fquellec requested changes
Nice way of handling days !

2022-08-23 08:20 UTC, fquellec commented on experiences/components/chart/view/ChartViewOverviewUber.vue
>                <a class="reset" style="display: none">reset</a>
We have a translation key for reset too: 
`<a class="reset" style="display: none" v-t="'reset'"></a>`

2022-08-25 08:46 UTC, valentinoli commented
Commit 7d35e92 should have the following commit message: `fix: use $n() method options to round numbers`

2022-09-05 09:19 UTC, valentinoli reviewed
Approve

2022-09-05 09:44 UTC, merged